title: Allan M. de Azevedo
description: 1 + 1 = 10
author: Allan
github_username: 4llan

markdown: kramdown
theme: minima

minima:
  date_format: "%Y-%m-%d"

header_external_links:
  - title: Rankings FGV
    url: https://rankings-fgv.allan.eti.br/

plugins:
  - jekyll-feed
  - jeyll-seo-tags
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
